<?php
/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function lalsearch_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#lalsearch":
      $output = '<p>'.  t("Searches into LAL metadata repository") .'</p>';
      break;
  }
  return $output;
} //function lalsearch_help
?>

<?php
/**
 * Implementation of hook_block().
 * @param string $op one of "list", "view", "save" and "configure"
 * @param integer $delta code to identify the block
 * @param array $edit only for "save" operation
*/
function lalsearch_block($op = 'list', $delta = 0, $edit = array()) {  
  if ($op == "list") {
    // Generate listing of blocks from this module, for the admin/block page
    $block = array();
    $block[0]["info"] = t('LAL Search');
    return $block;
  } 
  else if ($op = "view") {
    //Fake content
    $block_content = "First<br />Second<br />Third<br />";
    $block["subject"] = "Search results";
    $block["content"] = $block_content;
    return $block
  }
} // function lalsearch_block
?>

<?php
/**
* Valid permissions for this module
* @return array An array of valid permissions for the lalsearch module
*/
function lalsearch_perm() {
  return array('access LAL metadata content');
} // function lalsearch_perm()
