<?php
/**
 * Display help and module information
 * @param path which path of the site we're displaying help
 * @param arg array that holds the current path as would be returned from arg() function
 * @return help text for the path
 */
function lalsearch_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#lalsearch":
      $output = '<p>'.  t("Searches into LAL metadata repository") .'</p>';
      break;
  }
  return $output;
} //function lalsearch_help
?>

<?php
/**
* Valid permissions for this module
* @return array An array of valid permissions for the lalsearch module
*/
function lalsearch_perm() {
  return array('access LAL metadata content');
} // function lalsearch_perm()
